# Generated by Django 3.1.7 on 2021-05-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=255, verbose_name='Аватарка')),
                ('username', models.CharField(max_length=255, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(blank=True, default='None', max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, default='None', max_length=255, verbose_name='Фамилия')),
            ],
        ),
    ]
