# Generated by Django 3.1.7 on 2021-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210527_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyuser',
            name='password2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proxyuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
