# Generated by Django 3.0.7 on 2020-12-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_start', models.TimeField()),
                ('case_end', models.TimeField()),
                ('case', models.CharField(max_length=50)),
                ('case_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('baseday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timetable.BaseDay')),
            ],
            bases=('timetable.baseday',),
        ),
        migrations.AddField(
            model_name='baseday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.User'),
        ),
    ]
