# Generated by Django 3.0.7 on 2020-12-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friday',
            options={'verbose_name': '5 Пятница', 'verbose_name_plural': '5 Пятница'},
        ),
        migrations.AlterModelOptions(
            name='monday',
            options={'verbose_name': '1 Понедельник', 'verbose_name_plural': '1 Понедельник'},
        ),
        migrations.AlterModelOptions(
            name='saturday',
            options={'verbose_name': '6 Суббота', 'verbose_name_plural': '6 Суббота'},
        ),
        migrations.AlterModelOptions(
            name='sunday',
            options={'verbose_name': '7 Воскресенье', 'verbose_name_plural': '7 Воскресенье'},
        ),
        migrations.AlterModelOptions(
            name='thursday',
            options={'verbose_name': '4 Четверг', 'verbose_name_plural': '4 Четверг'},
        ),
        migrations.AlterModelOptions(
            name='tuesday',
            options={'verbose_name': '2 Вторник', 'verbose_name_plural': '2 Вторник'},
        ),
        migrations.AlterModelOptions(
            name='wednesday',
            options={'verbose_name': '3 Среда', 'verbose_name_plural': '3 Среда'},
        ),
    ]
