# Generated by Django 3.0.7 on 2020-12-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('timetable', '0003_auto_20201220_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
