# Generated by Django 3.1.4 on 2020-12-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20201222_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseday',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
