version: '3.7'
services:

  web:
    build: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 7070:8000
    volumes:
      - ./api/:/usr/src/api/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:

      
