# Generated by Django 3.2.3 on 2021-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210527_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
